" MY VIMRC

" switch from the default Vi-compatibility mode so as to enable useful
" vim functionality.
set nocompatible

" set leader and localleader keys
let mapleader = " "
let maplocalleader = ","

" clear autocmds in case file is sourced again
augroup my_autocmds
    autocmd!
augroup END


" disable the default Vim startup message.
" dont pass messages to |ins-completion-menu|
set shortmess+=I
set shortmess+=c

" without this option, whenever you switch buffers and your current buffer
" not saved, vim will prompt you to save the file
set hidden

" no swapfile, no backups
set noswapfile nobackup nowritebackup undofile
set undodir=~/.vim/undodir " you have to mkdir

" enable mouse support
set mouse+=a

" disable audible bell because it's annoying
set noerrorbells visualbell t_vb=

" set encoding to utf-8 because why not
set encoding=utf-8

" enable file detection and indent scripts
filetype on

" jump to the matching bracket briefly when a bracket is inserted
set showmatch matchtime=3

" make backspace behave more reasonably
set backspace=indent,eol,start

" make vim paste copied text from the external program without
" having to use `=*p` or `=+p`
set clipboard=unnamed

" do not display mode in statusline, will be displayed by statusbar
set noshowmode

" remove default wrapping
set nowrap


" add line numbering
set number numberwidth=5
set relativenumber

" give more space for displaying messages
set cmdheight=1

" for folding
set foldmethod=indent
set foldlevel=99

" set tabs to 4 characters, spaces
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab

" let vim try do a smart job in indentations
set smartindent

" enable autoindent
set autoindent
filetype plugin indent on

" incremental highlighting for search
set hlsearch incsearch

" for clearing highlighting after a search
nnoremap <silent> \ :<C-u>nohlsearch<CR>

" use ripgrep for external grep
set grepprg=rg\ --vimgrep\ --smart-case\ --follow

" center to line when searching
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz

" ignorecase makes all searches case-insensitive
" smartcase overrides the ignorecase option if the search pattern contains
" at least one uppercase character. That is, if there's an uppercase
" character, the search becomes case-sensistive
" For situations where you want to override ignorecase for an all-lowercase
" search patter, append \C to the pattern, for example /foo\C will not match
" Foo and FOO
set ignorecase smartcase

" add key combos for navigating between split windows
" ctrl+k move to split window above
" ctrl+l move to split window on the right
" ctrl+h move to spit window on the left
" ctrl+j move to split window below
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" on splitting windows, open new file on right or below
set splitbelow
set splitright

" Unbind some useless/annoying default key bindings.
" 'Q' in normal mode enters Ex mode. You almost never want this.
nnoremap Q <Nop>

" keep current buffer only
nnoremap <Leader>o :w<CR>:%bd \| e# \| bd# <CR>

" automatically install vim-plug
let s:data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(s:data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.s:data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
    Plug 'ap/vim-buftabline'
    " add tmux navigation compatibility
    Plug 'christoomey/vim-tmux-navigator'
    " disable tmux navigator when zooming the Vim pane
    let g:tmux_navigator_disable_when_zoomed = 1

    " tim-pope's, for quick navigation of lists
    Plug 'tpope/vim-unimpaired'
    " add tim-pope's commentary plugin
    Plug 'tpope/vim-commentary'

    "" add tim-pope's surround plugin to simplify quoting/wrapping text
    Plug 'tpope/vim-surround'

    " for autoclosing {},(),[],"",'',``
    Plug 'jiangmiao/auto-pairs'

    " theme with minimal coloring
    Plug 'huyvohcmc/atlas.vim'
call plug#end()

" set width to 80 characters
set colorcolumn=80
highlight ColorColumn ctermbg=grey guibg=darkgrey

" styling
set background=dark
syntax enable
colorscheme atlas
